import HomeSection from "@/components/Home/HomeSection";

export const metadata = {
  title: "Day 10 || Home",
  description: "Generated by create next app",
};
const Home = () => {
  return (
    <main className="min-h-screen">
      <HomeSection />
    </main>
  );
};

export default Home;
