import DashboardNavbar from "@/components/DashboardNavbar/DashboardNavbar";
import Sidebar from "@/components/Sidebar/Sidebar";
import React from "react";

export const metadata = {
  title: "Day 10 || Dashboard",
  description: "Generated by create next app",
};

const WithDashboardLayout = ({ children }) => {
  return (
    <main className="h-screen flex">
      <Sidebar />
      <div className="flex flex-col w-full">
        <DashboardNavbar />
        {children}
      </div>
    </main>
  );
};

export default WithDashboardLayout;
